apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: fuzzy2332/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000