apiVersion: v1
kind: Pod
metadata:
  name: online-inference-prob
  labels:
    app: online-inference-prob
spec:
  containers:
    - image: fuzzy2332/online_inference:v2
      name: online-inference-prob
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
